spring:
  datasource:
    url: jdbc:postgresql://db:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  data:
    redis:
      host: redis
      port: 6379

cloud:
  aws:
    s3:
      endpoint: ${R2_ENDPOINT}
    credentials:
      access-key: ${R2_ACCESS_KEY}
      secret-key: ${R2_SECRET_KEY}

kis:
  base-url: ${KIS_BASE_URL}
  app-key: ${KIS_APP_KEY}
  app-secret: ${KIS_APP_SECRET}