server:
  port: 8080

spring:
  application:
    name: yogimangchi

  datasource:
    url: jdbc:postgresql://localhost:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  data:
    redis:
      host: localhost
      port: 6379

cloud:
  aws:
    s3:
      endpoint: ${R2_ENDPOINT}
    credentials:
      access-key: ${R2_ACCESS_KEY}
      secret-key: ${R2_SECRET_KEY}

binance:
  websocket-url: wss://stream.binance.com:9443
  tracked-symbols:
    - BTCUSDT
    - ETHUSDT
    - XRPUSDT
